plugins {
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
}

group = 'com.astilett.neocolony'
version = '1.0.0'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        client {
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                neocolony_modpack {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven {
        url "https://maven.blamejared.com"
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.10'
    compileOnly fg.deobf("vazkii.patchouli:Patchouli:1.20.1-84-FORGE")
}
