modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="neocolony_modpack"
version="1.0.0"
displayName="NeoColony Modpack Guide"
authors="Astilett"
description='''Добавляет внутриигровое руководство по модпаку NeoColony.'''

[[dependencies.neocolony_modpack]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.neocolony_modpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"