plugins {
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'org.spongepowered.mixin' version '0.7.+'
}

group = 'com.astilett.epictweak'
version = '1.0.0'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    runs {
        client {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                epictweak {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    // Только для Patchouli
    maven {
        url "https://maven.blamejared.com"
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.4.10'
    implementation files('libs/epicfight-forge-20.12.4-1.20.1.jar')
    
    // Patchouli (компиляция, игрок должен установить мод самостоятельно)
    compileOnly fg.deobf("vazkii.patchouli:Patchouli:1.20.1-84-FORGE")
    // Для тестов в среде разработки можно добавить runtimeOnly, если Patchouli лежит в mods
    // runtimeOnly fg.deobf("vazkii.patchouli:Patchouli:1.20.1-84-FORGE")
    
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
    add sourceSets.main, "epictweak.refmap.json"
    config "epictweak.mixins.json"
}